# Generated by Django 6.0.4 on 2026-05-02 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_chat_profile_delete_chatmessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chat',
        ),
    ]
